/**
 * main screen current account
 * @autor. Komarofky.
 */
package Cliente;

import Facturacion.Conexion;
import Principal.VentanaPrincipal;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komarofky
 */
public class CuentaCorriente extends javax.swing.JFrame {

    /**
     * Creates new form CuentaCorriente
     */
    public CuentaCorriente() throws SQLException {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        /*HACE QUE LA VENTANA OCUPE TODA LA PANTALLA*/
        DefaultTableModel modelo = (DefaultTableModel) TablaCuentaCorriente.getModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("RAZON SOCIAL");
        modelo.addColumn("NOMBRE COMERCIAL");
        modelo.addColumn("DOCUMENTO");
        modelo.addColumn("SALDO");
        Conexion sc = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
        Object[] registros;
        registros = new Object[8];
        String query6 = "select ven_cc.cod_cliente, razon_social, nom_comercial, num_dni, monto_total from facturacion.ven_cc join facturacion.ven_cliente on ven_cliente.cod_cliente = ven_cc.cod_cliente";
        PreparedStatement statement6 = sc.getConnectio().prepareStatement(query6);
        ResultSet re = statement6.executeQuery();

        while (re.next()) {
            registros[0] = re.getInt("cod_cliente");
            registros[1] = re.getString("razon_social");
            registros[2] = re.getString("nom_comercial");
            registros[3] = re.getString("num_dni");
            registros[4] = re.getString("monto_total");
            ((DefaultTableModel) TablaCuentaCorriente.getModel()).addRow(registros);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nuevo_pago = new javax.swing.JButton();
        ModificarCliente = new javax.swing.JButton();
        Salir_cliente = new javax.swing.JButton();
        NombreTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCuentaCorriente = new javax.swing.JTable();
        BuscarCliente = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Nuevo_pago.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Nuevo_pago.setText("NUEVO PAGO");
        Nuevo_pago.setPreferredSize(new java.awt.Dimension(122, 36));
        Nuevo_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_pagoActionPerformed(evt);
            }
        });

        ModificarCliente.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        ModificarCliente.setText("CONSULTAR");
        ModificarCliente.setPreferredSize(new java.awt.Dimension(122, 36));
        ModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarClienteActionPerformed(evt);
            }
        });

        Salir_cliente.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Salir_cliente.setText("SALIR");
        Salir_cliente.setPreferredSize(new java.awt.Dimension(122, 36));
        Salir_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_clienteActionPerformed(evt);
            }
        });

        NombreTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Vera Serif", 1, 20), new java.awt.Color(0, 0, 0))); // NOI18N
        NombreTabla.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N

        TablaCuentaCorriente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TablaCuentaCorriente.setFont(new java.awt.Font("Ubuntu", 2, 20)); // NOI18N
        TablaCuentaCorriente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaCuentaCorriente.setFocusable(false);
        TablaCuentaCorriente.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaCuentaCorriente.setRowHeight(30);
        TablaCuentaCorriente.getTableHeader().setReorderingAllowed(false);
        TablaCuentaCorriente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCuentaCorrienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCuentaCorriente);

        BuscarCliente.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        BuscarCliente.setText("BUSCAR:");

        Aceptar.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Aceptar.setText("ACEPTAR");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NombreTablaLayout = new javax.swing.GroupLayout(NombreTabla);
        NombreTabla.setLayout(NombreTablaLayout);
        NombreTablaLayout.setHorizontalGroup(
            NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NombreTablaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreTablaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        NombreTablaLayout.setVerticalGroup(
            NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreTablaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NombreTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(Nuevo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(ModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(Salir_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(NombreTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nuevo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salir_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * new current account payment
     * @param evt 
     */
    private void Nuevo_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_pagoActionPerformed

        int row = TablaCuentaCorriente.getSelectedRow();
        if (row != -1) {
            this.dispose();
            NuevoPago np = new NuevoPago();
            np.setVisible(true);
            String codigo = TablaCuentaCorriente.getValueAt(row, 0).toString();
            String razonsocial = TablaCuentaCorriente.getValueAt(row, 1).toString();
            String monto = TablaCuentaCorriente.getValueAt(row, 4).toString();

            np.getCodigo().setText(codigo);
            np.getRazonSocial().setText(razonsocial);
            np.getDeuda().setText(monto);
        }

    }//GEN-LAST:event_Nuevo_pagoActionPerformed

    /**
     * modify client
     * @param evt 
     */
    private void ModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarClienteActionPerformed
        int row = TablaCuentaCorriente.getSelectedRow();
        if (row != -1) {
            this.dispose();
            ConsultarCC cc = new ConsultarCC();
            cc.setVisible(true);
            String codigo = TablaCuentaCorriente.getValueAt(row, 0).toString();
            String razonsocial = TablaCuentaCorriente.getValueAt(row, 1).toString();
            String monto = TablaCuentaCorriente.getValueAt(row, 4).toString();

            cc.getCodigo().setText(codigo);
            cc.getRazonSocial().setText(razonsocial);
            cc.getDeuda().setText(monto);
        }
    }//GEN-LAST:event_ModificarClienteActionPerformed

    /**
     * close client module
     * @param evt 
     */
    private void Salir_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_clienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_Salir_clienteActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * modify client with double mouse click
     * @param evt 
     */
    private void TablaCuentaCorrienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCuentaCorrienteMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = TablaCuentaCorriente.getSelectedRow();
            if (row != -1) {
                this.dispose();
                ConsultarCC cc = new ConsultarCC();
                cc.setVisible(true);
                String codigo = TablaCuentaCorriente.getValueAt(row, 0).toString();
                String razonsocial = TablaCuentaCorriente.getValueAt(row, 1).toString();
                String monto = TablaCuentaCorriente.getValueAt(row, 4).toString();

                cc.getCodigo().setText(codigo);
                cc.getRazonSocial().setText(razonsocial);
                cc.getDeuda().setText(monto);
            }
        }
    }//GEN-LAST:event_TablaCuentaCorrienteMouseClicked

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentaCorriente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentaCorriente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentaCorriente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentaCorriente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CuentaCorriente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CuentaCorriente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel BuscarCliente;
    private javax.swing.JButton ModificarCliente;
    private javax.swing.JPanel NombreTabla;
    private javax.swing.JButton Nuevo_pago;
    private javax.swing.JButton Salir_cliente;
    private javax.swing.JTable TablaCuentaCorriente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
