/**
 * tittle: NuevoCliente
 * new client, client module.
 * @autor. Komarofky.
 */

package Cliente;

import Avisos.*;
import Facturacion.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author komarofky
 */
public class NuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        this.setLocationRelativeTo(null);   /*HACE QUE LA VENTANA SE CENTRE EN EL MEDIO DE LA PANTALLA*/
    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatosClientes = new javax.swing.JTabbedPane();
        DatosGenerales = new javax.swing.JPanel();
        Razon_Social = new javax.swing.JLabel();
        razonsocial = new javax.swing.JTextField();
        Nombre_Comercial = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        TIpo_Dni = new javax.swing.JLabel();
        opciones_dni = new javax.swing.JComboBox<>();
        Numero_Dni = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        Categoria_Iva = new javax.swing.JLabel();
        tipo_iva = new javax.swing.JComboBox<>();
        Ingresos_Brutos = new javax.swing.JLabel();
        numero_ingresos = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Cond_Venta = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Guardar1 = new javax.swing.JButton();
        DatosAdicionales = new javax.swing.JPanel();
        Codigo_Postal = new javax.swing.JLabel();
        codigo_postal = new javax.swing.JTextField();
        Telefono_Cliente = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        Celular = new javax.swing.JLabel();
        numero_celular = new javax.swing.JTextField();
        Mail_Cliente = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        Morosidad_Cliente = new javax.swing.JLabel();
        morosidad = new javax.swing.JTextField();
        Limite_Credito = new javax.swing.JLabel();
        limite_credito = new javax.swing.JTextField();
        Estado_Cliente = new javax.swing.JLabel();
        Opciones_Estado = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        Cancelar2 = new javax.swing.JButton();
        direccion = new javax.swing.JLabel();
        nomdireccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        DatosClientes.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 30)); // NOI18N
        DatosClientes.setPreferredSize(new java.awt.Dimension(595, 594));

        DatosGenerales.setPreferredSize(new java.awt.Dimension(1060, 570));

        Razon_Social.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Razon_Social.setText("RAZON SOCIAL");
        Razon_Social.setPreferredSize(new java.awt.Dimension(199, 24));

        razonsocial.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Nombre_Comercial.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Nombre_Comercial.setText("NOMBRE COMERICAL");

        nombre.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        TIpo_Dni.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        TIpo_Dni.setText("TIPO DNI");

        opciones_dni.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        opciones_dni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CUIT", "CUIL" }));

        Numero_Dni.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Numero_Dni.setText("NUMERO DNI");
        Numero_Dni.setPreferredSize(new java.awt.Dimension(199, 24));

        numero.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Categoria_Iva.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Categoria_Iva.setText("CATEGORIA DE IVA");

        tipo_iva.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        tipo_iva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONSUMIDOR FINAL", "RESPONSABLE INSCRIPTO", "RESPONSABLE MONOTRIBUTO", "SUJETO EXENTO" }));

        Ingresos_Brutos.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Ingresos_Brutos.setText("INGRESOS BRUTOS");
        Ingresos_Brutos.setPreferredSize(new java.awt.Dimension(199, 24));

        numero_ingresos.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Cancelar.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Cancelar.setText("CANCELAR");
        Cancelar.setPreferredSize(new java.awt.Dimension(122, 36));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Cond_Venta.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Cond_Venta.setText("COND. VENTA");

        jComboBox1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONTADO", "CUENTA CORRIENTE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Guardar1.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Guardar1.setText("GUARDAR");
        Guardar1.setPreferredSize(new java.awt.Dimension(122, 36));
        Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatosGeneralesLayout = new javax.swing.GroupLayout(DatosGenerales);
        DatosGenerales.setLayout(DatosGeneralesLayout);
        DatosGeneralesLayout.setHorizontalGroup(
            DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosGeneralesLayout.createSequentialGroup()
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosGeneralesLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatosGeneralesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TIpo_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cond_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Numero_Dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Categoria_Iva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ingresos_Brutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nombre_Comercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Razon_Social, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                            .addComponent(razonsocial)
                            .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(numero_ingresos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addComponent(numero, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tipo_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opciones_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosGeneralesLayout.setVerticalGroup(
            DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosGeneralesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Razon_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(razonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_Comercial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TIpo_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opciones_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Categoria_Iva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingresos_Brutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero_ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cond_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        DatosClientes.addTab("GENERAL", DatosGenerales);

        Codigo_Postal.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Codigo_Postal.setText("CODIGO POSTAL");
        Codigo_Postal.setPreferredSize(new java.awt.Dimension(199, 24));

        codigo_postal.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Telefono_Cliente.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Telefono_Cliente.setText("TELEFONO FIJO");
        Telefono_Cliente.setPreferredSize(new java.awt.Dimension(199, 24));

        telefono.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });

        Celular.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Celular.setText("CELULAR");
        Celular.setPreferredSize(new java.awt.Dimension(199, 24));

        numero_celular.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Mail_Cliente.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Mail_Cliente.setText("MAIL");
        Mail_Cliente.setPreferredSize(new java.awt.Dimension(199, 24));

        mail.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Morosidad_Cliente.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Morosidad_Cliente.setText("MOROSIDAD");
        Morosidad_Cliente.setPreferredSize(new java.awt.Dimension(199, 24));

        morosidad.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Limite_Credito.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Limite_Credito.setText("LIMITE DE CREDITO");
        Limite_Credito.setMaximumSize(new java.awt.Dimension(199, 24));
        Limite_Credito.setPreferredSize(new java.awt.Dimension(199, 24));

        limite_credito.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Estado_Cliente.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Estado_Cliente.setText("ESTADO ");
        Estado_Cliente.setPreferredSize(new java.awt.Dimension(199, 24));

        Opciones_Estado.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Opciones_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HABILITADO", "SUSPENDIDO", "CANCELADO" }));

        Guardar.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.setPreferredSize(new java.awt.Dimension(122, 36));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar2.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Cancelar2.setText("CANCELAR");
        Cancelar2.setPreferredSize(new java.awt.Dimension(122, 36));
        Cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar2ActionPerformed(evt);
            }
        });

        direccion.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        direccion.setText("DIRECCION");
        direccion.setPreferredSize(new java.awt.Dimension(199, 24));

        nomdireccion.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        javax.swing.GroupLayout DatosAdicionalesLayout = new javax.swing.GroupLayout(DatosAdicionales);
        DatosAdicionales.setLayout(DatosAdicionalesLayout);
        DatosAdicionalesLayout.setHorizontalGroup(
            DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Telefono_Cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mail_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Morosidad_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Limite_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Codigo_Postal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Estado_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomdireccion)
                    .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                        .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codigo_postal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addComponent(numero_celular)
                                .addComponent(morosidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(limite_credito, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Opciones_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(Cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        DatosAdicionalesLayout.setVerticalGroup(
            DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codigo_postal)
                    .addComponent(Codigo_Postal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomdireccion)
                    .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telefono)
                    .addComponent(Telefono_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Mail_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Morosidad_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(morosidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(limite_credito)
                    .addComponent(Limite_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opciones_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        DatosClientes.addTab("ADICIONALES", DatosAdicionales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(DatosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DatosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * cancel action
     * @param evt 
     */
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        try {
            this.dispose();
            PantallaCliente pc = new PantallaCliente();
            pc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * cancel action
     * @param evt 
     */
    private void Cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar2ActionPerformed
        try {
            this.dispose();
            PantallaCliente pc = new PantallaCliente();
            pc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Cancelar2ActionPerformed

    /**
     * save a new client}
     * check number dni
     * @param evt 
     */
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        try {
            Conexion sc = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
            String query5 = "INSERT INTO facturacion.ven_cliente (razon_social, nom_comercial, tipo_dni, num_dni, cat_iva, ing_brutos, cond_venta,codigo_postal,localidad, direccion, tel_fijo, celular, mail, morosidad, limite_credito, estado) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement statement5 = sc.getConnectio().prepareStatement(query5);
            
            /*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

            int codpos = Integer.parseInt(codigo_postal.getText());
            int moro = Integer.parseInt(morosidad.getText());
            float limcred = Float.parseFloat(limite_credito.getText());
            
            /*------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
          
            statement5.setString(1, razonsocial.getText());
            statement5.setString(2, nombre.getText());
            statement5.setString(3, (String) opciones_dni.getSelectedItem());
            /*
             * check number dni
             */
            String query3 = "SELECT num_dni FROM facturacion.ven_cliente WHERE num_dni = '" + numero.getText() + "'";
            PreparedStatement statement4 = sc.getConnectio().prepareStatement(query3);
            ResultSet res3 = statement4.executeQuery();
            if (res3.next()) {
                /*
                 * exists 
                 */
                dniExistente ciu = new dniExistente();
                ciu.setVisible(true);

            } else {
                /*
                 * not exists 
                 */
                statement5.setString(4, numero.getText());
            }
            statement5.setString(5, (String) tipo_iva.getSelectedItem());

            /*
             * check postal code
             */
            String query4 = "SELECT ing_brutos FROM facturacion.ven_cliente WHERE ing_brutos = '" + numero_ingresos.getText() + "'";
            PreparedStatement statement6 = sc.getConnectio().prepareStatement(query4);
            ResultSet res4 = statement6.executeQuery();
            if (res4.next()) {
                /*
                 * exists 
                 */
                 ing_brutosExistente ing = new ing_brutosExistente();
                 ing.setVisible(true);

            } else {
                /*
                 * not exists 
                 */
                statement5.setString(6, numero_ingresos.getText());
            }
            statement5.setString(7, (String) jComboBox1.getSelectedItem());
            statement5.setInt(8, codpos);
            /*
             * check postal code
             */
            String query = "SELECT cod_postal FROM facturacion.Localidades WHERE cod_postal = '" + codpos + "'";
            PreparedStatement statement2 = sc.getConnectio().prepareStatement(query);
            ResultSet res = statement2.executeQuery();
            if (res.next()) {
                /*
                 * exists 
                 */
                String query1 = "SELECT nombre FROM facturacion.Localidades WHERE cod_postal = '" + codpos + "'";
                PreparedStatement statement3 = sc.getConnectio().prepareStatement(query1);
                ResultSet res1 = statement3.executeQuery();
                res1.next();
                statement5.setString(9, res1.getString(1));
            } else {
                /*
                 * not exists 
                 */
                CiudadNoExistente ciu = new CiudadNoExistente();
                ciu.setVisible(true);
               
            }
            statement5.setString(10, nomdireccion.getText());
            statement5.setString(11, telefono.getText());
            statement5.setString(12, numero_celular.getText());
            statement5.setString(13, mail.getText());
            statement5.setInt(14, moro);
            statement5.setFloat(15, limcred);
            statement5.setString(16, (String) Opciones_Estado.getSelectedItem());
            statement5.executeUpdate();
            try {
                this.dispose();
                PantallaCliente pc = new PantallaCliente();
                pc.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * save a new client
     * check number dni
     * @param evt 
     */
    private void Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar1ActionPerformed
        try {
            Conexion sc = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
            String query5 = "INSERT INTO facturacion.ven_cliente (razon_social, nom_comercial, tipo_dni, num_dni, cat_iva, ing_brutos, cond_venta,codigo_postal,localidad, direccion, tel_fijo, celular, mail, morosidad, limite_credito, estado) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement statement5 = sc.getConnectio().prepareStatement(query5);

            /*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
            
           
            int codpos = Integer.parseInt(codigo_postal.getText());
            int moro = Integer.parseInt(morosidad.getText());
            float limcred = Float.parseFloat(limite_credito.getText());

            /*------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
          
            statement5.setString(1, razonsocial.getText());
            statement5.setString(2, nombre.getText());
            statement5.setString(3, (String) opciones_dni.getSelectedItem());
            /*
             * check number dni
             */
            String query3 = "SELECT num_dni FROM facturacion.ven_cliente WHERE num_dni = '" + numero.getText() + "'";
            PreparedStatement statement4 = sc.getConnectio().prepareStatement(query3);
            ResultSet res3 = statement4.executeQuery();
            if (res3.next()) {
                /*
                 * exists 
                 */
                dniExistente doc = new dniExistente();
                doc.setVisible(true);

            } else {
                /*
                 * not exists 
                 */
                statement5.setString(4, numero.getText());
            }
            statement5.setString(5, (String) tipo_iva.getSelectedItem());
            /**
             * check number ing_brutos
             */
            String query4 = "SELECT ing_brutos FROM facturacion.ven_cliente WHERE ing_brutos = '" + numero_ingresos.getText() + "'";
            PreparedStatement statement6 = sc.getConnectio().prepareStatement(query4);
            ResultSet res4 = statement6.executeQuery();
            if (res4.next()) {
                /*
                 * exists
                 */
                 ing_brutosExistente ing = new ing_brutosExistente();
                 ing.setVisible(true);

            } else {
                /*
                 * not exists
                 */
                statement5.setString(6, numero_ingresos.getText());
            }
            statement5.setString(7, (String) jComboBox1.getSelectedItem());
            statement5.setInt(8, codpos);
            /*
             * check postal code
             */
            String query = "SELECT cod_postal FROM facturacion.Localidades WHERE cod_postal = '" + codpos + "'";
            PreparedStatement statement2 = sc.getConnectio().prepareStatement(query);
            ResultSet res = statement2.executeQuery();
            if (res.next()) {
                /*
                 * exists
                 */
                String query1 = "SELECT nombre FROM facturacion.Localidades WHERE cod_postal = '" + codpos + "'";
                PreparedStatement statement3 = sc.getConnectio().prepareStatement(query1);
                ResultSet res1 = statement3.executeQuery();
                res1.next();
                statement5.setString(9, res1.getString(1));
            } else {
                /*
                 * not exists 
                 */
                CiudadNoExistente ciu = new CiudadNoExistente();
                ciu.setVisible(true);
            }
            statement5.setString(10, nomdireccion.getText());
            statement5.setString(11, telefono.getText());
            statement5.setString(12, numero_celular.getText());
            statement5.setString(13, mail.getText());
            statement5.setInt(14, moro);
            statement5.setInt(15, (int) limcred);
            statement5.setString(16, (String) Opciones_Estado.getSelectedItem());
            statement5.executeUpdate();
            try {
                this.dispose();
                PantallaCliente pc = new PantallaCliente();
                pc.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Guardar1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new NuevoCliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Cancelar2;
    private javax.swing.JLabel Categoria_Iva;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Codigo_Postal;
    private javax.swing.JLabel Cond_Venta;
    private javax.swing.JPanel DatosAdicionales;
    private javax.swing.JTabbedPane DatosClientes;
    private javax.swing.JPanel DatosGenerales;
    private javax.swing.JLabel Estado_Cliente;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JLabel Ingresos_Brutos;
    private javax.swing.JLabel Limite_Credito;
    private javax.swing.JLabel Mail_Cliente;
    private javax.swing.JLabel Morosidad_Cliente;
    private javax.swing.JLabel Nombre_Comercial;
    private javax.swing.JLabel Numero_Dni;
    private javax.swing.JComboBox<String> Opciones_Estado;
    private javax.swing.JLabel Razon_Social;
    private javax.swing.JLabel TIpo_Dni;
    private javax.swing.JLabel Telefono_Cliente;
    private javax.swing.JTextField codigo_postal;
    private javax.swing.JLabel direccion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField limite_credito;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField morosidad;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nomdireccion;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField numero_celular;
    private javax.swing.JTextField numero_ingresos;
    private javax.swing.JComboBox<String> opciones_dni;
    private javax.swing.JTextField razonsocial;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox<String> tipo_iva;
    // End of variables declaration//GEN-END:variables
}
