/**
 * New article
 *
 * @autor. Komarofky.
 */
package Stock;

import Avisos.ArticuloExistente;
import Avisos.StockMaxMin;
import DataBase.Conexion;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Komarofky.
 */
public class NuevoArticulo extends javax.swing.JFrame {

    /**
     * Creates new form NuevoStock
     */
    public NuevoArticulo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatosClientes = new javax.swing.JTabbedPane();
        DatosGenerales = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        cod_articulo = new javax.swing.JTextField();
        codigo_barra = new javax.swing.JLabel();
        cod_barra = new javax.swing.JTextField();
        nombre_articulo = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        des_articulo = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        Guardar1 = new javax.swing.JButton();
        nom_articulo = new javax.swing.JTextField();
        estado_arti = new javax.swing.JComboBox<>();
        DatosAdicionales = new javax.swing.JPanel();
        precio_compra = new javax.swing.JLabel();
        precio_c = new javax.swing.JTextField();
        precio_venta = new javax.swing.JLabel();
        precio_ven = new javax.swing.JTextField();
        tipo_iv = new javax.swing.JLabel();
        precio_final = new javax.swing.JLabel();
        precio_fin = new javax.swing.JTextField();
        stock_ = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        stock_mini = new javax.swing.JLabel();
        stock_min = new javax.swing.JTextField();
        stock_maxi = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Cancelar2 = new javax.swing.JButton();
        margen = new javax.swing.JLabel();
        margen_arti = new javax.swing.JTextField();
        stock_max = new javax.swing.JTextField();
        tipo_iva = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        DatosClientes.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 30)); // NOI18N
        DatosClientes.setPreferredSize(new java.awt.Dimension(595, 594));

        DatosGenerales.setPreferredSize(new java.awt.Dimension(1060, 570));

        codigo.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        codigo.setText("CODIGO");
        codigo.setPreferredSize(new java.awt.Dimension(199, 24));

        codigo_barra.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        codigo_barra.setText("CODIGO DE BARRA");

        nombre_articulo.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        nombre_articulo.setText("NOMBRE");

        descripcion.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        descripcion.setText("DESCRIPCION");
        descripcion.setPreferredSize(new java.awt.Dimension(199, 24));

        estado.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        estado.setText("ESTADO");

        Cancelar.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        Cancelar.setText("CANCELAR");
        Cancelar.setPreferredSize(new java.awt.Dimension(122, 36));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Guardar1.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Guardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png"))); // NOI18N
        Guardar1.setText("GUARDAR");
        Guardar1.setPreferredSize(new java.awt.Dimension(122, 36));
        Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar1ActionPerformed(evt);
            }
        });

        estado_arti.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        estado_arti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HABILITADO", "SUSPENDIDO", "CANCELADO" }));

        javax.swing.GroupLayout DatosGeneralesLayout = new javax.swing.GroupLayout(DatosGenerales);
        DatosGenerales.setLayout(DatosGeneralesLayout);
        DatosGeneralesLayout.setHorizontalGroup(
            DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nombre_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codigo_barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(des_articulo, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(cod_barra)
                    .addComponent(cod_articulo)
                    .addComponent(nom_articulo)
                    .addComponent(estado_arti, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(DatosGeneralesLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        DatosGeneralesLayout.setVerticalGroup(
            DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosGeneralesLayout.createSequentialGroup()
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosGeneralesLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(codigo_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosGeneralesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cod_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombre_articulo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(nom_articulo))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(des_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado_arti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        DatosClientes.addTab("GENERAL", DatosGenerales);

        precio_compra.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        precio_compra.setText("PRECIO COMPRA");
        precio_compra.setPreferredSize(new java.awt.Dimension(199, 24));

        precio_venta.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        precio_venta.setText("PRECIO NETO");
        precio_venta.setPreferredSize(new java.awt.Dimension(199, 24));

        precio_ven.setEditable(false);
        precio_ven.setBackground(java.awt.Color.white);
        precio_ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_venActionPerformed(evt);
            }
        });

        tipo_iv.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        tipo_iv.setText("TASA DE IVA");
        tipo_iv.setPreferredSize(new java.awt.Dimension(199, 24));

        precio_final.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        precio_final.setText("PRECIO DE VENTA");
        precio_final.setPreferredSize(new java.awt.Dimension(199, 24));

        precio_fin.setEditable(false);
        precio_fin.setBackground(java.awt.Color.white);

        stock_.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        stock_.setText("STOCK");
        stock_.setPreferredSize(new java.awt.Dimension(199, 24));

        stock_mini.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        stock_mini.setText("STOCK MIN");
        stock_mini.setMaximumSize(new java.awt.Dimension(199, 24));
        stock_mini.setPreferredSize(new java.awt.Dimension(199, 24));

        stock_maxi.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        stock_maxi.setText("STOCK MAX");
        stock_maxi.setPreferredSize(new java.awt.Dimension(199, 24));

        Guardar.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png"))); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.setPreferredSize(new java.awt.Dimension(122, 36));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar2.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Cancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        Cancelar2.setText("CANCELAR");
        Cancelar2.setPreferredSize(new java.awt.Dimension(122, 36));
        Cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar2ActionPerformed(evt);
            }
        });

        margen.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        margen.setText("MARGEN(%)");
        margen.setPreferredSize(new java.awt.Dimension(199, 24));

        tipo_iva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10.5", "21", "27" }));

        javax.swing.GroupLayout DatosAdicionalesLayout = new javax.swing.GroupLayout(DatosAdicionales);
        DatosAdicionales.setLayout(DatosAdicionalesLayout);
        DatosAdicionalesLayout.setHorizontalGroup(
            DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(precio_venta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(stock_mini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precio_compra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(margen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipo_iv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precio_final, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stock_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stock_maxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(precio_fin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(precio_c, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tipo_iva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precio_ven, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(margen_arti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock_min, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock_max, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(Cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        DatosAdicionalesLayout.setVerticalGroup(
            DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(precio_c, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(precio_compra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(margen_arti, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(margen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(precio_ven, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(precio_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipo_iva)
                    .addComponent(tipo_iv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(precio_fin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(precio_final, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(stock_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stock_min, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(stock_mini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stock_max, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(stock_maxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        DatosClientes.addTab("ADICIONALES", DatosAdicionales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DatosClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DatosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * cancel action
     * @param evt
     */
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();

        try {
            PantallaArticulo pa = new PantallaArticulo();
            pa.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CancelarActionPerformed

    @SuppressWarnings("empty-statement")

    /**
     * save a new article
     * check the code of the article does not exist
     * @param evt
     */

    private void Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar1ActionPerformed

        try {
            Conexion sc = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
            String query5 = "INSERT INTO facturacion.Articulo (cod_articulo, EAN, nombre, descripsion , precio_compra , margen , precio_venta , iva , precio_final , stock , stock_minimo, stock_maximo , estado) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement statement5 = sc.getConnectio().prepareStatement(query5);

            float precio_compra = Float.parseFloat(precio_c.getText());
            float marg = Float.parseFloat(margen_arti.getText());
            float iv = Float.parseFloat((String) tipo_iva.getSelectedItem());
            float precio_venta_calculado = ((marg * precio_compra) / 100) + precio_compra;
            float precio_final_calculado = ((iv * precio_venta_calculado) / 100) + precio_venta_calculado;
            int stk = Integer.parseInt(stock.getText());
            int stk_min = Integer.parseInt(stock_min.getText());
            int stk_max = Integer.parseInt(stock_max.getText());

            /*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
            String query3 = "SELECT cod_articulo FROM facturacion.Articulo WHERE cod_articulo = '" + cod_articulo.getText() + "'";
            PreparedStatement statement4 = sc.getConnectio().prepareStatement(query3);
            ResultSet res3 = statement4.executeQuery();
            if (res3.next()) {
                /**
                 * exist
                 */
                ArticuloExistente a = new ArticuloExistente();
                a.setVisible(true);

            } else {
                /**
                 * not exist
                 */
                statement5.setString(1, cod_articulo.getText());
            }

            statement5.setString(2, cod_barra.getText());
            statement5.setString(3, nom_articulo.getText());
            statement5.setString(4, des_articulo.getText());

            /*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
            statement5.setFloat(5, precio_compra);
            statement5.setFloat(6, marg);
            statement5.setFloat(7, precio_venta_calculado);
            statement5.setString(8, (String) tipo_iva.getSelectedItem());
            statement5.setFloat(9, precio_final_calculado);
            statement5.setInt(10, stk);
            if (stk_max < stk_min) {
                StockMaxMin s = new StockMaxMin();
                s.setVisible(true);
            } else {
                statement5.setInt(11, stk_min);
                statement5.setInt(12, stk_max);
            }

            statement5.setString(13, (String) estado_arti.getSelectedItem());
            statement5.executeUpdate();
            this.dispose();
            PantallaArticulo pa = new PantallaArticulo();
            pa.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(NuevoArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Guardar1ActionPerformed

    /**
     * save a new article
     * @param evt
     */

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        try {
            Conexion sc = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
            String query5 = "INSERT INTO facturacion.Articulo (cod_articulo, EAN, nombre, descripsion , precio_compra , margen , precio_venta , iva , precio_final , stock , stock_minimo, stock_maximo , estado) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement statement5 = sc.getConnectio().prepareStatement(query5);

            float precio_compra = Float.parseFloat(precio_c.getText());
            float marg = Float.parseFloat(margen_arti.getText());
            float iv =  Float.parseFloat((String) tipo_iva.getSelectedItem());
            float precio_venta_calculado = ((marg * precio_compra)/100) + precio_compra;
            float precio_final_calculado = ((iv * precio_venta_calculado) / 100) + precio_venta_calculado;
            int stk = Integer.parseInt(stock.getText());
            int stk_min = Integer.parseInt(stock_min.getText());
            int stk_max = Integer.parseInt(stock_max.getText());

            /*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
            statement5.setString(1, cod_articulo.getText());
            statement5.setString(2, cod_barra.getText());
            statement5.setString(3, nom_articulo.getText());
            statement5.setString(4, des_articulo.getText());

            /*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
            statement5.setFloat(5, precio_compra);
            statement5.setFloat(6, marg);
            statement5.setFloat(7, precio_venta_calculado);
            statement5.setString(8, (String) tipo_iva.getSelectedItem());
            statement5.setFloat(9, precio_final_calculado);
            statement5.setInt(10, stk);
            statement5.setInt(11, stk_min);
            statement5.setInt(12, stk_max);
            statement5.setString(13, (String) estado_arti.getSelectedItem());
            statement5.executeUpdate();
            this.dispose();
            PantallaArticulo pa = new PantallaArticulo();
            pa.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(NuevoArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * cancel action
     * @param evt
     */

    private void Cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar2ActionPerformed
        this.dispose();

        try {
            PantallaArticulo pa = new PantallaArticulo();
            pa.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Cancelar2ActionPerformed

    private void precio_venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_venActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_venActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Cancelar2;
    private javax.swing.JPanel DatosAdicionales;
    private javax.swing.JTabbedPane DatosClientes;
    private javax.swing.JPanel DatosGenerales;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JTextField cod_articulo;
    private javax.swing.JTextField cod_barra;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel codigo_barra;
    private javax.swing.JTextField des_articulo;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel estado;
    private javax.swing.JComboBox<String> estado_arti;
    private javax.swing.JLabel margen;
    private javax.swing.JTextField margen_arti;
    private javax.swing.JTextField nom_articulo;
    private javax.swing.JLabel nombre_articulo;
    private javax.swing.JTextField precio_c;
    private javax.swing.JLabel precio_compra;
    private javax.swing.JTextField precio_fin;
    private javax.swing.JLabel precio_final;
    private javax.swing.JTextField precio_ven;
    private javax.swing.JLabel precio_venta;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel stock_;
    private javax.swing.JTextField stock_max;
    private javax.swing.JLabel stock_maxi;
    private javax.swing.JTextField stock_min;
    private javax.swing.JLabel stock_mini;
    private javax.swing.JLabel tipo_iv;
    private javax.swing.JComboBox<String> tipo_iva;
    // End of variables declaration//GEN-END:variables
}
