/**
 * Company data
 * @autor. Komarofky.
 */

package Empresa;

import Avisos.CiudadNoExistente;
import Facturacion.Conexion;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Komarofky.
 */

public class NuevaEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form NuevaEmpresa
     */
    
    public NuevaEmpresa() {
        initComponents();
        this.setLocationRelativeTo(null);   /*HACE QUE LA VENTANA SE CENTRE EN EL MEDIO DE LA PANTALLA*/
    }

    /**
     * This method is called from within the constructor to initialize the form
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatosClientes = new javax.swing.JTabbedPane();
        DatosGenerales = new javax.swing.JPanel();
        razons = new javax.swing.JLabel();
        razonSocial = new javax.swing.JTextField();
        nombref = new javax.swing.JLabel();
        nombreFantasia = new javax.swing.JTextField();
        categoriai = new javax.swing.JLabel();
        tipod = new javax.swing.JLabel();
        numeroDni = new javax.swing.JTextField();
        dni = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        Guardar1 = new javax.swing.JButton();
        categoriaIva = new javax.swing.JComboBox<>();
        tipoDni = new javax.swing.JComboBox<>();
        DatosAdicionales = new javax.swing.JPanel();
        numIngresos = new javax.swing.JLabel();
        ingresosBrutos = new javax.swing.JTextField();
        direc = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        codpostal = new javax.swing.JLabel();
        codigoPostal = new javax.swing.JTextField();
        tel = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        Mail = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        pag = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Cancelar2 = new javax.swing.JButton();
        inicioAct = new javax.swing.JLabel();
        inicioActividades = new javax.swing.JTextField();
        pagWeb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DatosClientes.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 30)); // NOI18N
        DatosClientes.setPreferredSize(new java.awt.Dimension(595, 594));

        DatosGenerales.setPreferredSize(new java.awt.Dimension(1060, 570));

        razons.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        razons.setText("RAZON SOCIAL");
        razons.setPreferredSize(new java.awt.Dimension(199, 24));

        nombref.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        nombref.setText("NOMBRE DE FANTASIA");

        categoriai.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        categoriai.setText("CATEGORIA DE IVA");

        tipod.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        tipod.setText("TIPO DOCUMENTO");
        tipod.setPreferredSize(new java.awt.Dimension(199, 24));

        numeroDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDniActionPerformed(evt);
            }
        });

        dni.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        dni.setText("NUMERO DE DOCUMENTO");

        Cancelar.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Cancelar.setText("CANCELAR");
        Cancelar.setPreferredSize(new java.awt.Dimension(122, 36));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Guardar1.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Guardar1.setText("GUARDAR");
        Guardar1.setPreferredSize(new java.awt.Dimension(122, 36));
        Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar1ActionPerformed(evt);
            }
        });

        categoriaIva.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        categoriaIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONSUMIDOR FINAL", "RESPONSABLE INSCRIPTO", "RESPONSABLE MONOTRIBUTO", "SUJETO EXENTO" }));

        tipoDni.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        tipoDni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CUIT", "CUIL" }));

        javax.swing.GroupLayout DatosGeneralesLayout = new javax.swing.GroupLayout(DatosGenerales);
        DatosGenerales.setLayout(DatosGeneralesLayout);
        DatosGeneralesLayout.setHorizontalGroup(
            DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(razons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoriai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreFantasia)
                    .addComponent(categoriaIva, 0, 369, Short.MAX_VALUE)
                    .addComponent(razonSocial)
                    .addComponent(numeroDni, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(DatosGeneralesLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DatosGeneralesLayout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(tipoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(290, Short.MAX_VALUE)))
        );
        DatosGeneralesLayout.setVerticalGroup(
            DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosGeneralesLayout.createSequentialGroup()
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosGeneralesLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(nombref, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosGeneralesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(razonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(razons, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(nombreFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaIva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tipod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroDni, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(DatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DatosGeneralesLayout.createSequentialGroup()
                    .addGap(238, 238, 238)
                    .addComponent(tipoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );

        DatosClientes.addTab("GENERAL", DatosGenerales);

        numIngresos.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        numIngresos.setText("NUMERO INGRESOS BRUTOS");
        numIngresos.setPreferredSize(new java.awt.Dimension(199, 24));

        direc.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        direc.setText("DIRECCION");
        direc.setPreferredSize(new java.awt.Dimension(199, 24));

        codpostal.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        codpostal.setText("CODIGO POSTAL");
        codpostal.setPreferredSize(new java.awt.Dimension(199, 24));

        tel.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        tel.setText("TELEFONO");
        tel.setPreferredSize(new java.awt.Dimension(199, 24));

        Mail.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Mail.setText("MAIL");
        Mail.setMaximumSize(new java.awt.Dimension(199, 24));
        Mail.setPreferredSize(new java.awt.Dimension(199, 24));

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });

        pag.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        pag.setText("PAGINA WEB");
        pag.setPreferredSize(new java.awt.Dimension(199, 24));

        Guardar.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.setPreferredSize(new java.awt.Dimension(122, 36));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar2.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Cancelar2.setText("CANCELAR");
        Cancelar2.setPreferredSize(new java.awt.Dimension(122, 36));
        Cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar2ActionPerformed(evt);
            }
        });

        inicioAct.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        inicioAct.setText("INICIO DE ACTIVIDADES");
        inicioAct.setPreferredSize(new java.awt.Dimension(199, 24));

        inicioActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActividadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatosAdicionalesLayout = new javax.swing.GroupLayout(DatosAdicionales);
        DatosAdicionales.setLayout(DatosAdicionalesLayout);
        DatosAdicionalesLayout.setHorizontalGroup(
            DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(direc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(Mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inicioAct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codpostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresosBrutos, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(direccion)
                    .addComponent(telefono)
                    .addComponent(mail)
                    .addComponent(pagWeb)
                    .addComponent(inicioActividades)
                    .addComponent(codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(Cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        DatosAdicionalesLayout.setVerticalGroup(
            DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresosBrutos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(numIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inicioActividades, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(inicioAct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(direc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codpostal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pag, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DatosAdicionalesLayout.createSequentialGroup()
                        .addComponent(pagWeb)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(DatosAdicionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        DatosClientes.addTab("ADICIONALES", DatosAdicionales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DatosClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DatosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * cancel action
     * @param evt 
     */
    
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * save the company's data
     * @param evt 
     */
    
    private void Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar1ActionPerformed
        try {
            
            Conexion em = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
            String query1 = "INSERT INTO facturacion.Empresa (razon_social, nombre_fantasia, cat_iva, tipo_dni, num_dni, ing_brutos, inicion_activ, direccion, codigo_postal, localidad, telefono, mail, pag_web) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement statement5 = em.getConnectio().prepareStatement(query1);
            statement5.setString(1, razonSocial.getText());
            statement5.setString(2, nombreFantasia.getText());
            statement5.setString(3, (String)categoriaIva.getSelectedItem());
            statement5.setString(4, (String)tipoDni.getSelectedItem());
            statement5.setString(5, numeroDni.getText());
            statement5.setString(6, ingresosBrutos.getText());
            statement5.setString(7, inicioActividades.getText());
            statement5.setString(8, direccion.getText());
            statement5.setInt(9, Integer.parseInt(codigoPostal.getText()));
            
            String query = "SELECT cod_postal FROM facturacion.Localidades WHERE cod_postal = '" + Integer.parseInt(codigoPostal.getText()) + "'";
            PreparedStatement statement2 = em.getConnectio().prepareStatement(query);
            ResultSet res = statement2.executeQuery();
            if (res.next()) {
                String query2 = "SELECT nombre FROM facturacion.Localidades WHERE cod_postal = '" + Integer.parseInt(codigoPostal.getText()) + "'";
                PreparedStatement statement3 = em.getConnectio().prepareStatement(query2);
                ResultSet res1 = statement3.executeQuery();
                res1.next();
                statement5.setString(10, res1.getString(1));
            } else {
                CiudadNoExistente ciu = new CiudadNoExistente();
                ciu.setVisible(true);
               
            }
            statement5.setString(11, telefono.getText());
            statement5.setString(12, mail.getText());
            statement5.setString(13, pagWeb.getText());
            statement5.executeUpdate();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(NuevaEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Guardar1ActionPerformed

    /**
     * Method to convert String to Date
     * @param fecha
     * @return 
     */
    
    public static Date ParseFecha(String fecha)
    {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = (Date) formato.parse(fecha);
        } 
        catch (ParseException ex) 
        {
            System.out.println(ex);
        }
        return fechaDate;
    }
    
    
    /**
     * save the company's data
     * @param evt 
     */
    
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
            
        
        try {
            
            Conexion em = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
            String query1 = "INSERT INTO facturacion.Empresa (razon_social, nombre_fantasia, cat_iva, tipo_dni, num_dni, ing_brutos, inicion_activ, direccion, codigo_postal, localidad, telefono, mail, pag_web) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement statement5 = em.getConnectio().prepareStatement(query1);
            statement5.setString(1, razonSocial.getText());
            statement5.setString(2, nombreFantasia.getText());
            statement5.setString(3, (String)categoriaIva.getSelectedItem());
            statement5.setString(4, (String)tipoDni.getSelectedItem());
            statement5.setString(5, numeroDni.getText());
            statement5.setString(6, ingresosBrutos.getText());
            statement5.setString(7, inicioActividades.getText());
            statement5.setString(8, direccion.getText());
            statement5.setInt(9, Integer.parseInt(codigoPostal.getText()));
            
            String query = "SELECT cod_postal FROM facturacion.Localidades WHERE cod_postal = '" + Integer.parseInt(codigoPostal.getText()) + "'";
            PreparedStatement statement2 = em.getConnectio().prepareStatement(query);
            ResultSet res = statement2.executeQuery();
            if (res.next()) {
                String query2 = "SELECT nombre FROM facturacion.Localidades WHERE cod_postal = '" + Integer.parseInt(codigoPostal.getText()) + "'";
                PreparedStatement statement3 = em.getConnectio().prepareStatement(query2);
                ResultSet res1 = statement3.executeQuery();
                res1.next();
                statement5.setString(10, res1.getString(1));
            } else {
                CiudadNoExistente ciu = new CiudadNoExistente();
                ciu.setVisible(true);
               
            }
            statement5.setString(11, telefono.getText());
            statement5.setString(12, mail.getText());
            statement5.setString(13, pagWeb.getText());
            statement5.executeUpdate();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(NuevaEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * cancel action
     * @param evt 
     */
    
    private void Cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cancelar2ActionPerformed

    private void numeroDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDniActionPerformed

    private void inicioActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioActividadesActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NuevaEmpresa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Cancelar2;
    private javax.swing.JPanel DatosAdicionales;
    private javax.swing.JTabbedPane DatosClientes;
    private javax.swing.JPanel DatosGenerales;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JLabel Mail;
    private javax.swing.JComboBox<String> categoriaIva;
    private javax.swing.JLabel categoriai;
    private javax.swing.JTextField codigoPostal;
    private javax.swing.JLabel codpostal;
    private javax.swing.JLabel direc;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel dni;
    private javax.swing.JTextField ingresosBrutos;
    private javax.swing.JLabel inicioAct;
    private javax.swing.JTextField inicioActividades;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nombreFantasia;
    private javax.swing.JLabel nombref;
    private javax.swing.JLabel numIngresos;
    private javax.swing.JTextField numeroDni;
    private javax.swing.JLabel pag;
    private javax.swing.JTextField pagWeb;
    private javax.swing.JTextField razonSocial;
    private javax.swing.JLabel razons;
    private javax.swing.JLabel tel;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox<String> tipoDni;
    private javax.swing.JLabel tipod;
    // End of variables declaration//GEN-END:variables
}
