/**
 * check current account
 * @autor. Komarofky.
 */
package Cliente;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Komarofky
 */
public class ConsultarCC extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCC
     */
    public ConsultarCC() {
        initComponents();
        this.setLocationRelativeTo(null);   /*HACE QUE LA PANTALLA SE CENTRE EN EL MEDIO DE LA PANTALLA*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreTabla = new javax.swing.JPanel();
        Cod_Cliente = new javax.swing.JLabel();
        razonSocial = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        Cod_Cliente2 = new javax.swing.JLabel();
        Cod_Cliente1 = new javax.swing.JLabel();
        Ecodigo2 = new javax.swing.JTextField();
        Cod_Cliente3 = new javax.swing.JLabel();
        Edeuda = new javax.swing.JTextField();
        Salir_cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        NombreTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NUEVO PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Vera Serif", 1, 20), new java.awt.Color(0, 0, 0))); // NOI18N
        NombreTabla.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N

        Cod_Cliente.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Cod_Cliente.setText("RAZON SOCIAL: ");
        Cod_Cliente.setPreferredSize(new java.awt.Dimension(199, 24));

        razonSocial.setEditable(false);
        razonSocial.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        codigo.setEditable(false);
        codigo.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Cod_Cliente2.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Cod_Cliente2.setText("CLIENTE");
        Cod_Cliente2.setPreferredSize(new java.awt.Dimension(199, 24));

        Cod_Cliente1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Cod_Cliente1.setText("FACTURAS EN DEUDA");
        Cod_Cliente1.setPreferredSize(new java.awt.Dimension(199, 24));

        Ecodigo2.setEditable(false);
        Ecodigo2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Ecodigo2.setText(" ...");
        Ecodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ecodigo2ActionPerformed(evt);
            }
        });

        Cod_Cliente3.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        Cod_Cliente3.setText("SALDO");
        Cod_Cliente3.setPreferredSize(new java.awt.Dimension(199, 24));

        Edeuda.setEditable(false);
        Edeuda.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        Salir_cliente.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Salir_cliente.setText("SALIR");
        Salir_cliente.setPreferredSize(new java.awt.Dimension(122, 36));
        Salir_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NombreTablaLayout = new javax.swing.GroupLayout(NombreTabla);
        NombreTabla.setLayout(NombreTablaLayout);
        NombreTablaLayout.setHorizontalGroup(
            NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreTablaLayout.createSequentialGroup()
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NombreTablaLayout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cod_Cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cod_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cod_Cliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Edeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(razonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NombreTablaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Cod_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ecodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(387, 387, 387))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreTablaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Salir_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        NombreTablaLayout.setVerticalGroup(
            NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreTablaLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cod_Cliente2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cod_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(razonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cod_Cliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cod_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ecodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(Salir_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombreTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NombreTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ecodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ecodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ecodigo2ActionPerformed

    private void Salir_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_clienteActionPerformed
        try {
            this.dispose();
            CuentaCorriente cc = new CuentaCorriente();
            cc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Salir_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCC().setVisible(true);
            }
        });
    }

    public JTextField getCodigo() {
        return codigo;
    }

    public JTextField getRazonSocial() {
        return razonSocial;
    }

    public JTextField getDeuda() {
        return Edeuda;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cod_Cliente;
    private javax.swing.JLabel Cod_Cliente1;
    private javax.swing.JLabel Cod_Cliente2;
    private javax.swing.JLabel Cod_Cliente3;
    private javax.swing.JTextField Ecodigo2;
    private javax.swing.JTextField Edeuda;
    private javax.swing.JPanel NombreTabla;
    private javax.swing.JButton Salir_cliente;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField razonSocial;
    // End of variables declaration//GEN-END:variables
}
