/**
 * main screen of the article
 * @autor. Komarofky.
 */

package Stock;

import Facturacion.Conexion;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komarofky.
 */

public class PantallaArticulo extends javax.swing.JFrame {

    /**
     * Creates new form PantallaArticulo
     * @throws java.sql.SQLException
     */
    public PantallaArticulo() throws SQLException {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        /*HACE QUE LA VENTANA OCUPE TODA LA PANTALLA*/
        DefaultTableModel modelo = (DefaultTableModel) TablaArticulo.getModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("CODIGO BARRA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("STOCK");
        modelo.addColumn("PRECIO");
        Conexion sc = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
        Object[] registros;
        registros = new Object[6];
        String query6 = "SELECT cod_articulo, EAN, nombre, descripsion, stock, precio_final FROM facturacion.Articulo";
        PreparedStatement statement6 = sc.getConnectio().prepareStatement(query6);
        ResultSet re = statement6.executeQuery();
        while (re.next()) {
            registros[0] = re.getString("cod_articulo");
            registros[1] = re.getString("EAN");
            registros[2] = re.getString("nombre");
            registros[3] = re.getString("descripsion");
            registros[4] = re.getInt("stock");
            registros[5] = re.getFloat("precio_final");
            ((DefaultTableModel) TablaArticulo.getModel()).addRow(registros);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArticulo = new javax.swing.JTable();
        BuscarCliente = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Salir_Articulo = new javax.swing.JButton();
        ModificarArticulo = new javax.swing.JButton();
        Nuevo_Movimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NombreTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ARTICULOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Vera Serif", 1, 20), new java.awt.Color(0, 0, 0))); // NOI18N
        NombreTabla.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N

        TablaArticulo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TablaArticulo.setFont(new java.awt.Font("Ubuntu", 2, 20)); // NOI18N
        TablaArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaArticulo.setFocusable(false);
        TablaArticulo.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaArticulo.setRowHeight(30);
        TablaArticulo.getTableHeader().setReorderingAllowed(false);
        TablaArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaArticuloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaArticulo);

        BuscarCliente.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 20)); // NOI18N
        BuscarCliente.setText("BUSCAR:");

        Aceptar.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Aceptar.setText("ACEPTAR");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NombreTablaLayout = new javax.swing.GroupLayout(NombreTabla);
        NombreTabla.setLayout(NombreTablaLayout);
        NombreTablaLayout.setHorizontalGroup(
            NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NombreTablaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreTablaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        NombreTablaLayout.setVerticalGroup(
            NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreTablaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(NombreTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        Salir_Articulo.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Salir_Articulo.setText("SALIR");
        Salir_Articulo.setPreferredSize(new java.awt.Dimension(122, 36));
        Salir_Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_ArticuloActionPerformed(evt);
            }
        });

        ModificarArticulo.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        ModificarArticulo.setText("MODIFICAR");
        ModificarArticulo.setPreferredSize(new java.awt.Dimension(122, 36));
        ModificarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarArticuloActionPerformed(evt);
            }
        });

        Nuevo_Movimiento.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 20)); // NOI18N
        Nuevo_Movimiento.setText("NUEVO");
        Nuevo_Movimiento.setPreferredSize(new java.awt.Dimension(122, 36));
        Nuevo_Movimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_MovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(Nuevo_Movimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(ModificarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(737, 737, 737)
                    .addComponent(Salir_Articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(216, Short.MAX_VALUE))
                .addComponent(NombreTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(755, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nuevo_Movimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(NombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(Salir_Articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarActionPerformed

    private void Salir_ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_ArticuloActionPerformed
        this.dispose();
    }//GEN-LAST:event_Salir_ArticuloActionPerformed

    /**
     * edit an article
     * @param evt 
     */
    private void ModificarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarArticuloActionPerformed
        try {
            int row = TablaArticulo.getSelectedRow();
            if (row != -1) {
                this.dispose();
                EditarArticulo eA = new EditarArticulo();
                eA.setVisible(true);
                String codArticulo = TablaArticulo.getValueAt(row, 0).toString();
                String codBarra = TablaArticulo.getValueAt(row, 1).toString();
                String nombreArticulo = TablaArticulo.getValueAt(row, 2).toString();
                String descArticulo = TablaArticulo.getValueAt(row, 3).toString();
                String stock = TablaArticulo.getValueAt(row, 4).toString();
                String precioFinal = TablaArticulo.getValueAt(row, 5).toString();

                eA.getCodigo().setText(codArticulo);
                eA.getCodigo_barra().setText(codBarra);
                eA.getNombre().setText(nombreArticulo);
                eA.getDescripcion().setText(descArticulo);
                eA.getStock().setText(stock);
                eA.getPrecioF().setText(precioFinal);

                Conexion sc = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
                String query7 = "SELECT precio_compra, margen, precio_venta, iva, stock_minimo, stock_maximo, estado FROM facturacion.Articulo WHERE cod_articulo = '" + codArticulo + "'";
                PreparedStatement statement7 = sc.getConnectio().prepareStatement(query7);
                ResultSet res = statement7.executeQuery();
                res.next();

                eA.getPrecioC().setText(res.getString("precio_compra"));
                eA.getMargen().setText(res.getString("margen"));
                eA.getPrecioV().setText(res.getString("precio_venta"));
                eA.getStockMin().setText(res.getString("stock_minimo"));
                eA.getStockMax().setText(res.getString("stock_maximo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PantallaArticulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ModificarArticuloActionPerformed

    /**
     * new movement
     * @param evt 
     */
    private void Nuevo_MovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_MovimientoActionPerformed
        NuevoMovimiento ms = new NuevoMovimiento();
        ms.setVisible(true);
    }//GEN-LAST:event_Nuevo_MovimientoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    /**
     * Creates new form PantallaArticulo with double click of the mouse
     * @param evt 
     */
    private void TablaArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaArticuloMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                int row = TablaArticulo.getSelectedRow();
                if (row != -1) {
                    this.dispose();
                    EditarArticulo eA = new EditarArticulo();
                    eA.setVisible(true);
                    String codArticulo = TablaArticulo.getValueAt(row, 0).toString();
                    String codBarra = TablaArticulo.getValueAt(row, 1).toString();
                    String nombreArticulo = TablaArticulo.getValueAt(row, 2).toString();
                    String descArticulo = TablaArticulo.getValueAt(row, 3).toString();
                    String stock = TablaArticulo.getValueAt(row, 4).toString();
                    String precioFinal = TablaArticulo.getValueAt(row, 5).toString();

                    eA.getCodigo().setText(codArticulo);
                    eA.getCodigo_barra().setText(codBarra);
                    eA.getNombre().setText(nombreArticulo);
                    eA.getDescripcion().setText(descArticulo);
                    eA.getStock().setText(stock);
                    eA.getPrecioF().setText(precioFinal);

                    Conexion sc = new Conexion("org.postgresql.Driver", "jdbc:postgresql://127.0.0.1:5432/postgres", "root", DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/postgres", "postgres", "root"), "postgres");
                    String query7 = "SELECT precio_compra, margen, precio_venta, iva, stock_minimo, stock_maximo, estado FROM facturacion.Articulo WHERE cod_articulo = '" + codArticulo + "'";
                    PreparedStatement statement7 = sc.getConnectio().prepareStatement(query7);
                    ResultSet res = statement7.executeQuery();
                    res.next();

                    eA.getPrecioC().setText(res.getString("precio_compra"));
                    eA.getMargen().setText(res.getString("margen"));
                    eA.getPrecioV().setText(res.getString("precio_venta"));
                    eA.getStockMin().setText(res.getString("stock_minimo"));
                    eA.getStockMax().setText(res.getString("stock_maximo"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(PantallaArticulo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_TablaArticuloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new PantallaArticulo().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PantallaArticulo.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel BuscarCliente;
    private javax.swing.JButton ModificarArticulo;
    private javax.swing.JPanel NombreTabla;
    private javax.swing.JButton Nuevo_Movimiento;
    private javax.swing.JButton Salir_Articulo;
    private javax.swing.JTable TablaArticulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
